# config/adhoc.conf — Variables de entorno para el nodo AD-HOC

ADHOC_IFACE=wlan0
ADHOC_SSID=ADHOC-STREAM
ADHOC_FREQ=2412
ADHOC_NET=192.168.99
ADHOC_MULTI=239.255.42.42
ADHOC_PORT=5004
ADHOC_PLAYER=mpv
ADHOC_MUSIC=/opt/adhoc-node/music
